[tool.poetry]
name = "pred-maint-ui-projects"
version = "0.1.0"
description = ""
authors = ["Yannick Bodin"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
taipy = "^3.1.1"
plotly = "^5.21.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
